---
title: "Retrieve, format, and impute environmental data associated with marine 'omics data sets"
date: today
author:
  - name: Shane L Hogle
    orcid: 0000-0003-2595-3863
    affiliation: 
      - name: University of Turku
        city: Turku
        state: Finland
        url: https://www.utu.fi/en
#abstract: > 
#  The abstract text can go here 
#  and also here ...
keywords:
  - Oceanography
  - Microbiology
  - Omics
license: "CC BY"
copyright: 
  holder: Shane L Hogle
  year: 2024
# citation: 
#   container-title: BioRxiv
#   volume: 
#   issue: 
#   doi: 
funding: "The author received no specific funding for this work."
#bibliography: references.bib
---

# Introduction

This is a collection of code that should serve to make it easier to programmatically access, filter, and manipulate environmental data from various projects that sampled the ocean along with some kind of 'Omics data. At the moment this includes:

1. [Tara Oceans](https://fondationtaraocean.org/en/expedition/tara-oceans/) expedition. The code downloads data directly from the [PANGAEA Data Publisher](https://www.pangaea.de/) (predominantly from here: <https://doi.pangaea.de/10.1594/PANGAEA.875582>) and saves slightly formatted versions locally for easy access. 
2. Other features will likely be incorporated here, stay tuned...

## Project Organization

We follow the convention that only raw, unmodified, unfiltered, and non-subsetted datafiles obtained directly from database sources (including journal article metadata) are placed in the `_data_raw` directory. These should never be modified or changed. All data derived from these `_data_raw` files (including modification, filtering, and subsetting) are placed in the `data` directory

## Availability

Various external databases are accessed and used here. This includes the [MIT DARWIN model](https://darwinproject.mit.edu/) accessed from [Simons Collaborative Marine Atlas Project](https://simonscmap.com/), and environmental measurements (hydrography, biogeochemistry) from [PANGAEA](https://doi.pangaea.de/10.1594/PANGAEA.875576). You will need to [register with Simons CMAP](https://simonscmap.com/register), obtain an API key, then download the `cmap4r` [package](https://simonscmap.github.io/cmap4r/index.html) in order to access data from the MIT DARWIN model. The rest of the databases don't have API access restrictions and they are accessed programatically in the scripts.

All data and code in this GitHub repository (<https://github.com/slhogle/omicsOceansEnvData>) is provided under [GNU AGPL3](https://www.gnu.org/licenses/agpl-3.0.html). The rendered project site is available at <https://slhogle.github.io/omicsOceansEnvData/>, which has been produced using [Quarto notebooks](https://quarto.org/). The content on the rendered site is released under the [CC BY 4.0.](https://creativecommons.org/licenses/by/4.0/) This repository hosts all code and data for this project including the code necessary to fully recreate the rendered webpage.

An archived release of the code here is available from Zenodo:

## Reproducibility

The project uses [`renv`](https://rstudio.github.io/renv/index.html) to create reproducible environment to execute the code in this project. [See here](https://rstudio.github.io/renv/articles/renv.html#collaboration) for a brief overview on collaboration and reproduction of the entire project. To get up and running you can do:

``` r
install.packages("renv")
renv::restore()
```

## Relevant references

1. Dutkiewicz, S., A.E. Hickman, O. Jahn, W.W. Gregg, C.B. Mouw, and M.J. Follows. (2015) Capturing optically important constituents and properties in a marine biogeochemical and ecosystem model. Biogeoscience, 12, 4447-4481 [doi:10.5194/bg-12-4447-2015](https://doi.org/10.5194/bg-12-4447-2015)
2. Forget, G., Campin, J.-M., Heimbach, P., Hill, C. N., Ponte, R. M., and Wunsch, C. (2015) ECCO version 4: an integrated framework for non-linear inverse modeling and global ocean state estimation, Geosci. Model Dev., 8, 3071-3104, [doi:10.5194/gmd-8-3071-2015](https://doi.org/10.5194/gmd-8-3071-2015)
3. Forget, G., D. Ferreira, and X. Liang. (2015) On the observability of turbulent transport rates by argo: supporting evidence from an inversion experiment. Ocean Science, 11, 839–853, [doi:10.5194/os-11-839-2015](https://doi.org/10.5194/os-11-839-2015)
4. Forget, G. and R. Ponte. (2015) The partition of regional sea level variability. Progress in Oceanography, 137, 173–195, [doi:10.1016/j.pocean.2015.06.002](https://doi.org/10.1016/j.pocean.2015.06.002) 
5. Forget, G., 2018: Initial, preliminary version of the CBIOMES-global model setup and documentation (Version v0.0.1). Zenodo. <http://doi.org/10.5281/zenodo.1343303>
6. Forget, G. (2019) Update MITgcm & DarwinProject elements (Version v0.1.0). Zenodo. http://doi.org/10.5281/zenodo.2653669
7. Ward, B.A., S. Dutkiewicz, O. Jahn, and M.J. Follows. (2012) A size-structured food-web model for the global ocean. Limnol. Oceanogr., 57, 1877-1891. [doi:10.4319/lo.2012.57.6.1877](https://doi.org/10.4319/lo.2012.57.6.1877)
8. Pesant, S. et al. (2015) Open science resources for the discovery and analysis of Tara Oceans data. Sci. Data 2:150023 [doi: 10.1038/sdata.2015.23](http://doi.org/10.1038/sdata.2015.23)
https://aslopubs.onlinelibrary.wiley.com/doi/10.1002/lom3.10439
9. Guidi, Lionel; Picheral, Marc; Pesant, Stephane; Tara Oceans Consortium, Coordinators; Tara Oceans Expedition, Participants (2017): Environmental context of all samples from the Tara Oceans Expedition (2009-2013), about sensor data in the targeted environmental feature. PANGAEA, <https://doi.org/10.1594/PANGAEA.875576>
10. Ashkezari MD, Hagen NR, Denholtz M, Neang A, Burns TC, Morales RL, Lee CP, Hill CN, Armbrust EV. 2021. Simons Collaborative Marine Atlas Project (Simons CMAP): An open‐source portal to share, visualize, and analyze ocean data. Limnol Oceanogr Methods 19:488–496. [doi: 10.1002/lom3.10439](https://doi.org/10.1002/lom3.10439)